package sipsa.presentacion.escritorio;

class DialogoMensaje extends javax.swing.JDialog {
    public enum Tipo {Error, Advertencia, Información}

    /** Creates new form DialogoMensaje */
    public DialogoMensaje(javax.swing.JDialog parent, Tipo tipo, String mensaje) {
        super(parent, true);
        initComponents();

        switch (tipo) {
            case Información:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-information.png")));
                break;
            case Advertencia:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-warning.png")));
                break;
            case Error:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-error.png")));
                break;
        }
        this.setTitle(tipo.toString());
        this.jLabelInformacion.setText(mensaje);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jLabelInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/start-here.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelInformacion.setText(":) Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButtonAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelInformacion;
    // End of variables declaration//GEN-END:variables

}
