/*
 * Sistemas de Informacion II 2009
 * Proyecto Sipsa
 */

/*
 * SipsaMenu.java
 *
 * Created on 13/06/2009, 17:14:43
 */

package sipsa.presentacion.escritorio;

import sipsa.Configuracion;
import sipsa.presentacion.interfaces.ISipsaMenu;

/**
 * Formulario del Menu Principal
 * @author Claudio Rodrigo Pereyra Diaz
 * @author Maria Eugenia Sanchez
 */
public class SipsaMenu extends javax.swing.JFrame {

    private ISipsaMenu controlador;

    /** Creates new form SipsaMenu
     * @param controlador Controlador del formulario
     */
    public SipsaMenu(ISipsaMenu controlador) {
        initComponents();
        Configuracion configuracion = Configuracion.getInstancia();
        this.setIconImage(configuracion.getIcono());
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonImportarProductosVenta = new javax.swing.JButton();
        jButtonAdministrarPac = new javax.swing.JButton();
        jButtonAdministrarTiposProductos = new javax.swing.JButton();
        jButtonAdministrarPv = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonReporteOTRealizadas = new javax.swing.JButton();
        jButtonReporteOTPendientes = new javax.swing.JButton();
        jButtonReporteOTVencidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipsa");
        setIconImages(getIconImages());
        setLocationByPlatform(true);
        setResizable(false);

        jButtonImportarProductosVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-open.png"))); // NOI18N
        jButtonImportarProductosVenta.setText("Importar Productos a la Venta");
        jButtonImportarProductosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarProductosVentaActionPerformed(evt);
            }
        });

        jButtonAdministrarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/categories/preferences-system.png"))); // NOI18N
        jButtonAdministrarPac.setText("Administrar Puntos de Atencion al Cliente");
        jButtonAdministrarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarPacActionPerformed(evt);
            }
        });

        jButtonAdministrarTiposProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/categories/applications-other.png"))); // NOI18N
        jButtonAdministrarTiposProductos.setText("Administrar Tipos de Productos");
        jButtonAdministrarTiposProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarTiposProductosActionPerformed(evt);
            }
        });

        jButtonAdministrarPv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/apps/preferences-desktop-theme.png"))); // NOI18N
        jButtonAdministrarPv.setText("Administrar Puntos de Venta");
        jButtonAdministrarPv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarPvActionPerformed(evt);
            }
        });

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/system-log-out.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonReporteOTRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTRealizadas.setText("Reporte Ordenes de Trabajo Realizadas");
        jButtonReporteOTRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTRealizadasActionPerformed(evt);
            }
        });

        jButtonReporteOTPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTPendientes.setText("Reporte Ordenes de Trabajo Pendientes");
        jButtonReporteOTPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTPendientesActionPerformed(evt);
            }
        });

        jButtonReporteOTVencidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTVencidas.setText("Reporte Ordenes de Trabajo Vencidas");
        jButtonReporteOTVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTVencidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdministrarTiposProductos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jButtonAdministrarPv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jButtonAdministrarPac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImportarProductosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReporteOTRealizadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jButtonReporteOTPendientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonReporteOTVencidas, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdministrarTiposProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdministrarPv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdministrarPac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportarProductosVenta)
                .addGap(18, 18, 18)
                .addComponent(jButtonReporteOTRealizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReporteOTPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReporteOTVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministrarTiposProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarTiposProductosActionPerformed
        this.controlador.administrarTipoProducto();
}//GEN-LAST:event_jButtonAdministrarTiposProductosActionPerformed

    private void jButtonImportarProductosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarProductosVentaActionPerformed
        this.controlador.importarArchivoProductos();
    }//GEN-LAST:event_jButtonImportarProductosVentaActionPerformed

    private void jButtonAdministrarPvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarPvActionPerformed
        this.controlador.administrarPv();
}//GEN-LAST:event_jButtonAdministrarPvActionPerformed

    private void jButtonAdministrarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarPacActionPerformed
        this.controlador.administrarPac();
}//GEN-LAST:event_jButtonAdministrarPacActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonReporteOTRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTRealizadasActionPerformed
        this.controlador.mostrarReporteOTRealizadas();
}//GEN-LAST:event_jButtonReporteOTRealizadasActionPerformed

    private void jButtonReporteOTPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTPendientesActionPerformed
        this.controlador.mostrarReporteOTPendientes();
}//GEN-LAST:event_jButtonReporteOTPendientesActionPerformed

    private void jButtonReporteOTVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTVencidasActionPerformed
        this.controlador.mostrarReporteOTVencidas();
    }//GEN-LAST:event_jButtonReporteOTVencidasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrarPac;
    private javax.swing.JButton jButtonAdministrarPv;
    private javax.swing.JButton jButtonAdministrarTiposProductos;
    private javax.swing.JButton jButtonImportarProductosVenta;
    private javax.swing.JButton jButtonReporteOTPendientes;
    private javax.swing.JButton jButtonReporteOTRealizadas;
    private javax.swing.JButton jButtonReporteOTVencidas;
    private javax.swing.JButton jButtonSalir;
    // End of variables declaration//GEN-END:variables

}
