/*
 * AdminClientes.java
 *
 * Created on 8 de abril de 2007, 23:29
 */

package Presentacion.Interfaces;

import Dominio.Aplicacion.Clientes;
import Dominio.Controladores.ControladorABM;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Mariano
 */
public class AdminClientes extends javax.swing.JDialog {
    
    ControladorABM controlador;
  
    /** Creates new form AdminClientes */
    public AdminClientes() {
        
        initComponents();
        controlador= new ControladorABM();       
        this.setTitle("Administrar Clientes");
        this.cargarPantalla();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLCliente = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox();
        jBConsultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Modificar = new javax.swing.JButton();
        Aviso = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLCliente.setText("Cliente");

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(53, 53, 53)
                .add(jLCliente)
                .add(15, 15, 15)
                .add(jCBCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(jBConsultar)
                .add(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLCliente)
                    .add(jBConsultar)
                    .add(jCBCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Apellido", "Nombre", "Fecha Alta", "DNI/CUIT", "Provincia", "Localidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Aviso.setEditable(false);

        cancelar.setText("Salir");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .add(Aviso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(Agregar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Modificar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBEliminar)
                        .add(46, 46, 46)
                        .add(cancelar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Agregar)
                    .add(Modificar)
                    .add(jBEliminar)
                    .add(cancelar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 22, Short.MAX_VALUE)
                .add(Aviso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-686)/2, (screenSize.height-365)/2, 686, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
// TODO add your handling code here:
        this.getParent().setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    
    
    
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
// TODO add your handling code here:
      try{
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        controlador.actCliente((Integer) defaultTableModel.getValueAt(jTable1.getSelectedRow(),0));
        
        this.refrescarPantalla();
      }catch(Exception e){
          Aviso.setText(e.getMessage()+" Error: Debe seleccionar un Cliente o realizar una búsqueda");
      }
       
    }//GEN-LAST:event_ModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
       try{
           DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
           controlador.eliminarCli((Integer) defaultTableModel.getValueAt(jTable1.getSelectedRow(),0));
           Aviso.setText("El cliente fue eliminado correctamente");
            this.refrescarPantalla();
       }catch(SQLException e){
           Aviso.setText(e.getMessage()+": "+"El cliente posee Presupuestos, no se puede eliminar");           
       }catch (Exception e){
           Aviso.setText(e.getMessage()+" Error: Debe seleccionar un Cliente o realizar una búsqueda");
       }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
           
            controlador.amCliente();
             this.refrescarPantalla();
           
            
    }//GEN-LAST:event_AgregarActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
       
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
       
        
        //Vaciar la tabla de presupuestos
        for (int i=defaultTableModel.getRowCount()-1; i>=0; i--){
            defaultTableModel.removeRow(i);
        }
        
        if (jCBCliente.getSelectedIndex() != 0){
           Clientes cli=controlador.getCliente(jCBCliente.getSelectedIndex());
            defaultTableModel.addRow( new Object[]{cli.getNumero(),cli.getApellido(),cli.getNombre(),cli.getFechaAlta(),cli.getCuit_dni(),cli.getProvincia(),cli.getLocalidad()});
        }else{
           Vector Lcli=controlador.getClientes();
           for(int i=0;i<Lcli.size();i++){
               Clientes cli=(Clientes)Lcli.elementAt(i);
               defaultTableModel.addRow( new Object[]{cli.getNumero(),cli.getApellido(),cli.getNombre(),cli.getFechaAlta(),cli.getCuit_dni(),cli.getProvincia(),cli.getLocalidad()});
           }
        }
        
       
    }//GEN-LAST:event_jBConsultarActionPerformed
    
    public void refrescarPantalla(){
       this.cargarPantalla();
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
             
        for (int i=defaultTableModel.getRowCount()-1; i>=0; i--){
            defaultTableModel.removeRow(i);
        }
        
        Vector Lcli=controlador.getClientes();
         for(int i=0;i<Lcli.size();i++){
               Clientes cli=(Clientes)Lcli.elementAt(i);
               defaultTableModel.addRow( new Object[]{cli.getNumero(),cli.getApellido(),cli.getNombre(),cli.getFechaAlta(),cli.getCuit_dni(),cli.getProvincia(),cli.getLocalidad()});
           }
    }
    
    public void cargarPantalla(){
        
         jCBCliente.removeAllItems();
        jCBCliente.addItem("Todos");
        Vector LClientes=controlador.getClientes();
        for(int i=0; i<LClientes.size(); i++){
            Clientes c = (Clientes)LClientes.elementAt(i);
            jCBCliente.addItem(c.getNombre()+" "+c.getApellido());
        }
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Aviso;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JComboBox jCBCliente;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
