/*
 * Sistemas de Informacion II 2009
 * Proyecto Sipsa
 */

package sipsa.presentacion.escritorio;

import java.awt.Image;
import java.awt.Toolkit;

import sipsa.presentacion.interfaces.ISipsaPacMenu;

/**
 * Formulario del Menu Principal
 * @author Claudio Rodrigo Pereyra Diaz
 * @author Maria Eugenia Sanchez
 */
public class SipsaPacMenu extends javax.swing.JFrame {

    private ISipsaPacMenu controlador;

    /** Creates new form SipsaPacMenu
     * @param controlador Controlador del formulario
     */
    public SipsaPacMenu(ISipsaPacMenu controlador) {
        initComponents();
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/sipsa/presentacion/recursos/Sipsa.png"));
        this.setIconImage(img);
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonABTiposProductos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonReporteOTRealizadas = new javax.swing.JButton();
        jButtonReporteOTPendientes = new javax.swing.JButton();
        jButtonReporteOTVencidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipsa");
        setIconImages(getIconImages());
        setLocationByPlatform(true);
        setResizable(false);

        jButtonABTiposProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/categories/applications-office.png"))); // NOI18N
        jButtonABTiposProductos.setText("Administrar Ordenes de Trabajo");
        jButtonABTiposProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonABTiposProductosActionPerformed(evt);
            }
        });

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/system-log-out.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonReporteOTRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTRealizadas.setText("Reporte Ordenes de Trabajo Realizadas");
        jButtonReporteOTRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTRealizadasActionPerformed(evt);
            }
        });

        jButtonReporteOTPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTPendientes.setText("Reporte Ordenes de Trabajo Pendientes");
        jButtonReporteOTPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTPendientesActionPerformed(evt);
            }
        });

        jButtonReporteOTVencidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tango-project/tango-icon-theme/16x16/actions/document-print-preview.png"))); // NOI18N
        jButtonReporteOTVencidas.setText("Reporte Ordenes de Trabajo Vencidas");
        jButtonReporteOTVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteOTVencidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonABTiposProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReporteOTRealizadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jButtonReporteOTPendientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jButtonReporteOTVencidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonABTiposProductos)
                .addGap(18, 18, 18)
                .addComponent(jButtonReporteOTRealizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReporteOTPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReporteOTVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonABTiposProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonABTiposProductosActionPerformed
        this.controlador.administrarOT();
}//GEN-LAST:event_jButtonABTiposProductosActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonReporteOTRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTRealizadasActionPerformed
        this.controlador.mostrarReporteOTRealizadas();
}//GEN-LAST:event_jButtonReporteOTRealizadasActionPerformed

    private void jButtonReporteOTPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTPendientesActionPerformed
        this.controlador.mostrarReporteOTPendientes();
}//GEN-LAST:event_jButtonReporteOTPendientesActionPerformed

    private void jButtonReporteOTVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteOTVencidasActionPerformed
        this.controlador.mostrarReporteOTVencidas();
}//GEN-LAST:event_jButtonReporteOTVencidasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonABTiposProductos;
    private javax.swing.JButton jButtonReporteOTPendientes;
    private javax.swing.JButton jButtonReporteOTRealizadas;
    private javax.swing.JButton jButtonReporteOTVencidas;
    private javax.swing.JButton jButtonSalir;
    // End of variables declaration//GEN-END:variables

}