package sipsa.presentacion.escritorio;

import sipsa.Configuracion;

/**
 * Dialogo para mostrar mensajes
 * @author Maria Eugenia Sanchez
 * @author Administrador
 */
public class DialogoMensaje extends javax.swing.JDialog {
    /**
     */
    public enum Tipo {

        /**
         * Enumerado de tipos de mensajes disponibles
         */
        Error, Advertencia,Información
    }

    /** Constructor para crear un nuevo dialogo de mensaje
     * @param tipo
     * @param mensaje
     */
    public DialogoMensaje(Tipo tipo, String mensaje) {
        Configuracion configuracion = Configuracion.getInstancia();
        this.setIconImage(configuracion.getIcono());
        initComponents();
        switch (tipo) {
            case Información:
                jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-information.png")));
                break;
            case Advertencia:
                jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-warning.png")));
                break;
            case Error:
                jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-error.png")));
                break;
        }
        this.setTitle(tipo.toString());
        this.jLabelInformacion.setText(mensaje);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jScrollPaneInformacion = new javax.swing.JScrollPane();
        jLabelInformacion = new javax.swing.JTextArea();
        jLabelIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/start-here.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelInformacion.setColumns(20);
        jLabelInformacion.setEditable(false);
        jLabelInformacion.setRows(5);
        jScrollPaneInformacion.setViewportView(jLabelInformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JTextArea jLabelInformacion;
    private javax.swing.JScrollPane jScrollPaneInformacion;
    // End of variables declaration//GEN-END:variables

}
