package sipsa.presentacion.escritorio;

import sipsa.Configuracion;

/**
 * Dialogo para mostrar mensajes
 * @author Maria Eugenia Sanchez
 * @author Administrador
 */
public class DialogoMensaje extends javax.swing.JDialog {
    /**
     */
    public enum Tipo {

        /**
         * Enumerado de tipos de mensajes disponibles
         */
        Error, Advertencia,Información
    }

    /** Constructor para crear un nuevo dialogo de mensaje
     * @param tipo
     * @param mensaje
     */
    public DialogoMensaje(Tipo tipo, String mensaje) {
        Configuracion configuracion = Configuracion.getInstancia();
        this.setIconImage(configuracion.getIcono());
        initComponents();
        switch (tipo) {
            case Información:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-information.png")));
                break;
            case Advertencia:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-warning.png")));
                break;
            case Error:
                jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-error.png")));
                break;
        }
        this.setTitle(tipo.toString());
        this.jLabelInformacion.setText(mensaje);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jLabelInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/start-here.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sipsa/presentacion/recursos/dialog-information.png"))); // NOI18N
        jLabelInformacion.setMaximumSize(new java.awt.Dimension(32, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addComponent(jButtonAceptar)
                    .addComponent(jLabelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelInformacion;
    // End of variables declaration//GEN-END:variables

}
